---
#RHEL,AMI暂时只支持AWS AMI
  - name: Ensure the repo on AMI
    become: yes
    become_user: root
#    yum_repository:
#      name: epel
#      state: present
    command: " yum-config-manager --enable epel"
    when: ansible_os_family == "RedHat"
